#config_version=5

mode:
  start_events: start_mode_left_loop
  stop_events: stop_mode_left_loop
  priority: 200

shots:
  left_loop:
    switch: s_left_loop

show_player:
  mode_left_loop_started:
    left_loop_strobe:
      speed: 6
      show_tokens:
        color: 8b3626

variable_player:
  left_loop_hit:
    score: 1234

event_player:
  left_loop_hit: stop_mode_left_loop, start_mode_left_loop_qualifier