#config_version=5

mode:
  start_events: ball_starting
  priority: 250

event_player:
  mode_house_achievements_started:
    - start_qualifiers
  house_started{device.achievements.stark.state!="enabled" and device.achievements.martell.state!="enabled" and device.achievements.tyrell.state!="enabled" and device.achievements.targaryen.state!="enabled" and device.achievements.lannister.state!="enabled" and device.achievements.baratheon.state!="enabled" and device.achievements.greyjoy.state!="enabled"}:
    - house_not_ready
  house_completed{device.achievements.stark.state=="enabled" or device.achievements.martell.state=="enabled" or device.achievements.tyrell.state=="enabled" or device.achievements.targaryen.state=="enabled" or device.achievements.lannister.state=="enabled" or device.achievements.baratheon.state=="enabled" or device.achievements.greyjoy.state=="enabled"}:
    - house_ready
  house_select_cancelled{device.achievements.stark.state=="enabled" or device.achievements.martell.state=="enabled" or device.achievements.tyrell.state=="enabled" or device.achievements.targaryen.state=="enabled" or device.achievements.lannister.state=="enabled" or device.achievements.baratheon.state=="enabled" or device.achievements.greyjoy.state=="enabled"}:
    - house_ready

achievements:
  stark:
    show_tokens:
      light: l_stark_sigil
      color: white
    sync_ms: 1000
    enable_events: stark_qualified
    show_when_enabled: flash_sync_color
    events_when_enabled: house_ready
    start_events: stark_started
    show_when_started: flash_sync_color
    events_when_started: house_started
    complete_events: stark_completed
    show_when_completed: led_color
    reset_events: reset_house_modes
    restart_on_next_ball_when_started: true
    start_enabled: false
  lannister:
    show_tokens:
      light: l_lannister_sigil
      color: red
    sync_ms: 1000
    enable_events: lannister_qualified
    show_when_enabled: flash_sync_color
    events_when_enabled: house_ready
    start_events: lannister_started
    show_when_started: flash_sync_color
    events_when_started: house_started
    complete_events: lannister_completed
    show_when_completed: led_color
    reset_events: reset_house_modes
    restart_on_next_ball_when_started: true
    start_enabled: false
  baratheon:
    show_tokens:
      light: l_baratheon_sigil
      color: yellow
    sync_ms: 1000
    enable_events: baratheon_qualified
    show_when_enabled: flash_sync_color
    events_when_enabled: house_ready
    start_events: baratheon_started
    show_when_started: flash_sync_color
    events_when_started: house_started
    complete_events: baratheon_completed
    show_when_completed: led_color
    reset_events: reset_house_modes
    restart_on_next_ball_when_started: true
    start_enabled: false
  tyrell:
    show_tokens:
      light: l_tyrell_sigil
      color: green
    sync_ms: 1000
    enable_events: tyrell_qualified
    show_when_enabled: flash_sync_color
    events_when_enabled: house_ready
    start_events: tyrell_started
    show_when_started: flash_sync_color
    events_when_started: house_started
    complete_events: tyrell_completed
    show_when_completed: led_color
    reset_events: reset_house_modes
    restart_on_next_ball_when_started: true
    start_enabled: false
  greyjoy:
    show_tokens:
      light: l_greyjoy_sigil
      color: purple
    sync_ms: 1000
    enable_events: greyjoy_qualified
    show_when_enabled: flash_sync_color
    events_when_enabled: house_ready
    start_events: greyjoy_started
    show_when_started: flash_sync_color
    events_when_started: house_started
    complete_events: greyjoy_completed
    show_when_completed: led_color
    reset_events: reset_house_modes
    restart_on_next_ball_when_started: true
    start_enabled: false
  martell:
    show_tokens:
      light: l_martell_sigil
      color: orange
    sync_ms: 1000
    enable_events: martell_qualified
    show_when_enabled: flash_sync_color
    events_when_enabled: house_ready
    start_events: martell_started
    show_when_started: flash_sync_color
    events_when_started: house_started
    complete_events: martell_completed
    show_when_completed: led_color
    reset_events: reset_house_modes
    restart_on_next_ball_when_started: true
    start_enabled: false
  targaryen:
    show_tokens:
      light: l_targaryen_sigil
      color: blue
    sync_ms: 1000
    enable_events: targaryen_qualified
    show_when_enabled: flash_sync_color
    events_when_enabled: house_ready
    start_events: targaryen_started
    show_when_started: flash_sync_color
    events_when_started: house_started
    complete_events: targaryen_completed
    show_when_completed: led_color
    reset_events: reset_house_modes
    restart_on_next_ball_when_started: true
    start_enabled: false

show_player:
  house_ready{current_player.house_running_count==0}:
    flash_sync_color:
      sync_ms: 1000
      show_tokens:
        light: l_choose_your_battle
        color: white
  house_not_ready:
    off:
      show_tokens:
        light: l_choose_your_battle
  house_started:
    off:
      key: turn_off_lights
      show_tokens:
        lights: house_sigils, shot_sigils
  player_house_running_count{value==0}:
    led_color:
      key: turn_off_lights
      show_tokens:
        lights: house_sigils, shot_sigils
        color: stop
  martell_completed:
    led_color:
      show_tokens:
        light: l_martell_sigil
        color: orange
  tyrell_completed:
    led_color:
      show_tokens:
        light: l_tyrell_sigil
        color: green
  greyjoy_completed:
    led_color:
      show_tokens:
        light: l_greyjoy_sigil
        color: purple
  lannister_completed:
    led_color:
      show_tokens:
        light: l_lannister_sigil
        color: red
  baratheon_completed:
    led_color:
      show_tokens:
        light: l_baratheon_sigil
        color: yellow
  targaryen_completed:
    led_color:
      show_tokens:
        light: l_targaryen_sigil
        color: blue
  stark_completed:
    led_color:
      show_tokens:
        light: l_stark_sigil
        color: white
