#config_version=5

mode:
  start_events: start_mode_greyjoy_qualifier
  stop_events: stop_mode_greyjoy_qualifier
  priority: 200

counters:
  greyjoy_shot_counter:
    count_events: s_left_loop_active
    events_when_hit: greyjoy_hit
    starting_count: 0
    count_complete_value: 3
    direction: up
    events_when_complete: greyjoy_qualified, stop_mode_greyjoy_qualifier
    persist_state: true

light_player:
  mode_greyjoy_qualifier_started:
    l_left_loop_sigil:
      color: purple

variable_player:
  greyjoy_hit{device.counters.greyjoy_shot_counter.value == 1}:
    score: 100000
  greyjoy_hit{device.counters.greyjoy_shot_counter.value == 2}:
    score: 200000
  greyjoy_qualified:
    score: 300000
  
