#config_version=5

mode:
  start_events: start_lannister
  stop_events: stop_lannister
  events_when_started: lannister_started
  events_when_stopped: lannister_completed, house_completed
  priority: 300

event_player:
  mode_lannister_started: stop_lannister

light_player:
  mode_lannister_started:
    shot_sigils: off
    house_sigils: off

show_player:
  mode_lannister_started:
    flash_sync_color:
      show_tokens:
        light: l_lannister_sigil
        color: red
