#config_version=5

mode:
  start_events: start_qualifiers{device.achievements.stark.state=="disabled"}
  stop_events: stop_mode_stark_qualifier, stop_qualifiers
  priority: 200

counters:
  stark_shot_counter:
    count_events: s_right_ramp_exit_active
    events_when_hit: stark_hit
    starting_count: 0
    count_complete_value: 3
    direction: up
    events_when_complete: stark_qualified, stop_mode_stark_qualifier
    persist_state: true
    disable_on_complete: false
    reset_on_complete: false

light_player:
  mode_stark_qualifier_started:
    l_right_ramp_sigil:
      color: white

variable_player:
  stark_hit{device.counters.stark_shot_counter.value == 1}:
    score: 100000
  stark_hit{device.counters.stark_shot_counter.value == 2}:
    score: 200000
  stark_qualified:
    score: 300000
  
