#config_version=5

mode:
  start_events: start_greyjoy
  stop_events: stop_greyjoy
  events_when_started: greyjoy_started
  events_when_stopped: greyjoy_completed, house_completed
  priority: 300

light_player:
  mode_greyjoy_started:
    l_choose_your_battle: off

counters:
  # temporary counter for testing
  debug_greyjoy_slingshot_counter:
    count_events: s_left_slingshot_active
    count_complete_value: 3
    events_when_complete: stop_greyjoy
    start_enabled: true

show_player:
  mode_greyjoy_started:
    flash_sync_color:
      sync_ms: 340
      show_tokens:
        light: l_greyjoy_sigil
        color: purple

blinkenlight_player:
  mode_greyjoy_started:
    bl_left_loop_sigil: purple
    bl_right_loop_sigil: purple
    bl_kickback_sigil: purple
    bl_left_ramp_sigil: purple
    bl_right_ramp_sigil: purple
