#config_version=5

mode:
  start_events: start_stark
  stop_events: stop_stark
  events_when_started: stark_started
  events_when_stopped: stark_completed, house_completed
  priority: 300

counters:
  # temporary counter for testing
  debug_stark_slingshot_counter:
    count_events: s_left_inlane_active
    count_complete_value: 3
    events_when_complete: stop_stark
    start_enabled: true

light_player:
  mode_stark_started:
    l_choose_your_battle: off

show_player:
  mode_stark_started:
    flash_sync_color:
      sync_ms: 340
      show_tokens:
        light: l_stark_sigil
        color: white

blinkenlight_player:
  mode_stark_started:
    bl_right_ramp_sigil: white
